#!/bin/bash

this_path=$(realpath -se "$0")

one_up=$(basename $(dirname $this_path))
two_up=$(basename $(dirname $(dirname $this_path)))
rest=$(dirname $(dirname $(dirname $this_path)))

if [ ${two_up} == "benchmarks" ]; then
    benchmark_root=$rest/$two_up
    benchmark_name=$one_up
    test_name=$one_up
else
    benchmark_root=$rest
    benchmark_name=$two_up
    test_name=$two_up/$one_up
fi
echo $benchmark_root
echo $test_name
echo $benchmark_name

