#!/bin/bash

this_path=$(realpath -se "$0")

one_up=$(basename $(dirname $this_path))
two_up=$(basename $(dirname $(dirname $this_path)))
rest=$(dirname $(dirname $(dirname $this_path)))

if [ ${two_up} == "benchmarks" ]; then
    benchmark_root=$rest/$two_up
    benchmark_name=$one_up
    test_name=$one_up
    container_name="hs-${one_up}"
else
    benchmark_root=$rest
    benchmark_name=$two_up
    test_name=$two_up/$one_up
    container_name="hs-${two_up}-${one_up}"
fi
# echo $benchmark_root
# echo $test_name
# echo $benchmark_name

rm -rf $benchmark_root/../output/$test_name
docker rm -f $container_name 2>/dev/null

# Run the benchmark (may exit with non-zero, but we still want to copy output files)
docker run --name $container_name --init --privileged --cgroupns=host -v /mydata/tmp:/tmp hs/${benchmark_name} ./report/benchmarks/${test_name}/run $@ || true
# docker run --name $container_name --init --privileged --cgroupns=host -v /mydata/tmp:/tmp -it hs/${benchmark_name} bash
mkdir -p $benchmark_root/../output/$test_name
# Copy all output files (will succeed even if files don't exist or container failed)
docker cp $container_name:/srv/hs/report/output/$test_name/error $benchmark_root/../output/$test_name/error 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/error_hs $benchmark_root/../output/$test_name/error_hs 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/error_pash $benchmark_root/../output/$test_name/error_pash 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/hs_time $benchmark_root/../output/$test_name/hs_time 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/sh_time $benchmark_root/../output/$test_name/sh_time 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/pash_time $benchmark_root/../output/$test_name/pash_time 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/hs/stderr $benchmark_root/../output/$test_name/stderr_hs 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/sh/stderr $benchmark_root/../output/$test_name/stderr_sh 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/pash/stderr $benchmark_root/../output/$test_name/stderr_pash 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/hs/stdout $benchmark_root/../output/$test_name/stdout_hs 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/sh/stdout $benchmark_root/../output/$test_name/stdout_sh 2>/dev/null || true
docker cp $container_name:/srv/hs/report/output/$test_name/pash/stdout $benchmark_root/../output/$test_name/stdout_pash 2>/dev/null || true
docker rm $container_name
