#!/bin/bash

SCRIPT_DIR="$( dirname -- "${BASH_SOURCE[0]}" )"
NAME="$SCRIPT_DIR/trimmomatic.jar"

if [ ! -e "$NAME"  ]; then
  echo "ERROR: Trimmomatic not found!" >&2
  exit 1
fi

# flags to prevent speculation conflicts, like with biostars-multiprocessing
java \
   -XX:-UsePerfData \
   -XX:-CreateCoredumpOnCrash \
   -XX:ErrorFile=/dev/null \
   -XX:+UnlockDiagnosticVMOptions \
   -XX:-DumpPrivateMappingsInCore \
   -XX:-DumpSharedMappingsInCore \
   -jar "$NAME" \
   "$@"
