sleep 0.5 | mkdir "$test_output_dir/1"
sleep 0.1 | mkdir "$test_output_dir/2"
echo "hello1" > "$test_output_dir/2/out1"
sleep 0.4 | mkdir "$test_output_dir/1/3"
sleep 0.3 | mkdir "$test_output_dir/1/3/4"
sleep 0.7 |echo "hello2" > "$test_output_dir/1/3/4/out1"
sleep 0.4 |echo "hello3" > "$test_output_dir/2/out2"
sleep 0.6 | grep hello2 "$test_output_dir/2/out2" > "$test_output_dir/2/out2"
sleep 0.2 | mkdir "$test_output_dir/1/3/4/5"
sleep 1   | mkdir "$test_output_dir/1/2/3"
echo "$test_output_dir/2/out2" > "$test_output_dir/2/out3"