echo "hello0" > ./output_orch/out0
echo "hello1" > ./output_orch/out1
echo "hello2" > ./output_orch/out2
echo "hello3" > ./output_orch/out3
echo "hello4" > ./output_orch/out4
echo "hello5" > ./output_orch/out5
echo "hello6" > ./output_orch/out6
echo "hello7" > ./output_orch/out7
echo "hello8" > ./output_orch/out8
echo "hello9" > ./output_orch/out9