echo "hello0" > ./output_bash/out0
echo "hello1" > ./output_bash/out1
echo "hello2" > ./output_bash/out2
echo "hello3" > ./output_bash/out3
echo "hello4" > ./output_bash/out4
echo "hello5" > ./output_bash/out5
echo "hello6" > ./output_bash/out6
echo "hello7" > ./output_bash/out7
echo "hello8" > ./output_bash/out8
echo "hello9" > ./output_bash/out9