name: Tests
on: 
  pull_request:
    branches:
    - main
    types: [assigned, opened, synchronize, reopened, ready_for_review]
    paths: 
    - .github/**
    - parallel-orch/**
    - overlay-sandbox/**
    - test/**
    - scripts/**
  push:
    branches:
    - main
    paths: 
    - parallel-orch/**
    - overlay-sandbox/**
    - test/**
    - scripts/**
  workflow_dispatch:

# Jobs section
jobs:
    PaSh-Spec-Tests:
      strategy:
        fail-fast: false
        matrix:
          os: 
          - ubuntu-22.04
      runs-on: ${{ matrix.os }}
      if: github.event.pull_request.draft == false
      steps:
      - uses: actions/checkout@v2 
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Running Correctness Tests
        run: |
          sudo touch /.githubenv
          # install the system deps and pash the environment
          sudo -E bash scripts/install_deps_ubuntu20.sh -o
          export PASH_TOP=$PWD
          export PATH=$PATH:$PASH_TOP
          # run all the tests (INTRO, INTERFACE, COMPILER)
          cd test && bash test_orch.sh  
          # get the timer
          timer=$(LANG=en_us_88591; date)
          echo "VERSION<<EOF" >> $GITHUB_ENV
          echo "OS:${{matrix.os}}" >> $GITHUB_ENV
          echo "$timer" >> $GITHUB_ENV
          # Parse the results and construct a github message post
          # we append the data to the global env
          cat results/results.log >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          script: |
            let body = `${{ env.VERSION }}`
            console.log(context)
            // if we are directly pushing on main/future, we cannot push comments -> exit
            if (context.eventName === "push" && (context.ref === "refs/heads/main" || context.ref === "refs/heads/future")) {
              return 0;
            }
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            })     
      - name: Exit Code
        run: |
          # check if everything executed without errors
          cd test && bash exit_code.sh
