name: Tests
on: 
  pull_request:
    branches:
    - main
    types: [assigned, opened, synchronize, reopened, ready_for_review]
    paths: 
    - .github/**
    - parallel-orch/**
    - overlay-sandbox/**
    - test/**
    - scripts/**
    - python_hs/**
  push:
    branches:
    - main
    paths: 
    - parallel-orch/**
    - overlay-sandbox/**
    - test/**
    - scripts/**
    - python_hs/**
  workflow_dispatch:
# Jobs section
jobs:
    PaSh-Spec-Tests:
      strategy:
        fail-fast: false
        matrix:
          os: 
          - ubuntu-20.04
      runs-on: ${{ matrix.os }}
      if: github.event.pull_request.draft == false
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup hS
        run: |
          uname -a
          # install the system deps and pash the environment
          sudo apt update
          sudo apt install -y strace wget make file libtool mergerfs util-linux curl netcat-openbsd
          git submodule update --init --recursive
          cd deps/pash
          sudo bash scripts/setup-pash.sh
      - name: Running Correctness Tests
        run: |
          bash test/test_orch.sh  
      - name: Running Python HS Tests
        run: |
          bash python_hs/tests/test.sh
         
