name: Tests
on:
  pull_request:
    branches:
    - main
    types: [assigned, opened, synchronize, reopened, ready_for_review]
    paths:
    - hs
    - .github/**
    - jit_runtime/**
    - scheduler/**
    - executor/**
    - preprocessor/**
    - overlay-sandbox/**
    - test/**
    - scripts/**
    - python_hs/**
  push:
    branches:
    - main
    paths:
    - hs
    - jit_runtime/**
    - scheduler/**
    - executor/**
    - preprocessor/**
    - overlay-sandbox/**
    - test/**
    - scripts/**
    - python_hs/**
  workflow_dispatch:
# Jobs section
jobs:
    PaSh-Spec-Tests:
      strategy:
        fail-fast: false
        matrix:
          os:
          - ubuntu-24.04
      runs-on: ${{ matrix.os }}
      if: github.event.pull_request.draft == false
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          uname -a
          sudo apt-get update
          sudo apt install -y make git python3-cram file graphviz libtool python3-matplotlib libcap2-bin mergerfs strace python3-venv python3-pip
          export PASH_SPEC_TOP=$(pwd)
          git submodule update --init --recursive deps/try
          python3.12 -m venv python_pkgs
          python_pkgs/bin/pip install --upgrade pip
          python_pkgs/bin/pip install -r requirements.txt
          python_pkgs/bin/pip install python_hs/ pytest
          python_pkgs/bin/pip install psutil
          python_pkgs/bin/python -c "import shasta; import libdash; import libbash"
          (cd executor; make)
      - name: Running hS Correctness Tests
        run: |
          export PASH_SPEC_TOP=$(pwd)
          DEBUG=100 bash test/test_orch.sh
      - name: Running Python hS Correctness Tests
        run: |
          python_pkgs/bin/pytest python_hs/
